import { useEffect, useState } from "react";
import api from "../../api/axios";
import { Printer, FileText, Bus, Fuel, Wrench, Ticket } from "lucide-react";

export default function Reports() {
  const [data, setData] = useState({});

  useEffect(() => {
    api.get("/dashboard").then((res) => setData(res.data.data || {}));
  }, []);

  const printReport = () => {
    window.print();
  };

  const estimatedProfit =
    (data.revenue || 0) -
    (data.fuelCosts || 0) -
    (data.maintenanceCosts || 0);

  return (
    <div>
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8 print-hidden">
        <div>
          <p className="text-[#7F1D1D] text-sm tracking-[0.3em] uppercase font-bold">
            Analytics
          </p>

          <h1 className="text-3xl sm:text-4xl font-black mt-2 text-gray-900">
            Reports Dashboard
          </h1>

          <p className="text-gray-500 mt-2">
            View fleet, revenue, fuel and maintenance performance summary.
          </p>
        </div>

        <button
          onClick={printReport}
          className="bg-[#7F1D1D] text-white font-bold px-5 py-3 rounded-xl hover:bg-[#991B1B] flex items-center justify-center gap-2 shadow-sm"
        >
          <Printer size={18} />
          Print / Save PDF
        </button>
      </div>

      <div
        id="print-report"
        className="bg-white border border-gray-200 rounded-3xl p-8 shadow-sm print:rounded-none print:shadow-none"
      >
        <div className="border-b border-gray-200 pb-6 mb-6">
          <p className="text-sm tracking-[0.3em] text-[#7F1D1D] font-bold">
            RUDRA EXPRESS
          </p>

          <h2 className="text-3xl font-black text-gray-900 mt-2">
            Operations Report
          </h2>

          <p className="text-gray-500 mt-1">
            Generated on {new Date().toLocaleString()}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <ReportCard icon={Bus} label="Total Buses" value={data.totalBuses || 0} />
          <ReportCard icon={Bus} label="Active Buses" value={data.activeBuses || 0} />
          <ReportCard icon={Wrench} label="Maintenance Buses" value={data.maintenanceBuses || 0} />
          <ReportCard icon={Ticket} label="Revenue" value={`Rs. ${data.revenue || 0}`} />
        </div>

        <section className="mb-8">
          <h3 className="text-xl font-black mb-4 flex items-center gap-2 text-gray-900">
            <FileText size={20} className="text-[#7F1D1D]" />
            Fleet Summary
          </h3>

          <table className="w-full border border-gray-200 text-sm rounded-xl overflow-hidden">
            <tbody>
              <Row label="Total Buses" value={data.totalBuses || 0} />
              <Row label="Active Buses" value={data.activeBuses || 0} />
              <Row label="Maintenance Buses" value={data.maintenanceBuses || 0} />
              <Row label="Total Routes" value={data.totalRoutes || 0} />
              <Row label="Total Drivers" value={data.totalDrivers || 0} />
              <Row label="Total Conductors" value={data.totalConductors || 0} />
            </tbody>
          </table>
        </section>

        <section className="mb-8">
          <h3 className="text-xl font-black mb-4 flex items-center gap-2 text-gray-900">
            <Fuel size={20} className="text-[#7F1D1D]" />
            Cost & Revenue Summary
          </h3>

          <table className="w-full border border-gray-200 text-sm rounded-xl overflow-hidden">
            <tbody>
              <Row label="Fuel Cost" value={`Rs. ${data.fuelCosts || 0}`} />
              <Row label="Maintenance Cost" value={`Rs. ${data.maintenanceCosts || 0}`} />
              <Row label="Revenue" value={`Rs. ${data.revenue || 0}`} />
              <Row label="Estimated Profit" value={`Rs. ${estimatedProfit}`} />
            </tbody>
          </table>
        </section>

        <section>
          <h3 className="text-xl font-black mb-4 text-gray-900">
            Operational Performance
          </h3>

          <table className="w-full border border-gray-200 text-sm rounded-xl overflow-hidden">
            <tbody>
              <Row label="Completed Trips" value={data.tripsCompleted || 0} />
              <Row label="Reported Incidents" value={data.incidents || 0} />
            </tbody>
          </table>
        </section>

        <div className="mt-10 pt-6 border-t border-gray-200 text-sm text-gray-500">
          This report was generated by RUDRA EXPRESS Fleet Management System.
        </div>
      </div>
    </div>
  );
}

function ReportCard({ icon: Icon, label, value }) {
  return (
    <div className="bg-gray-50 border border-gray-200 rounded-2xl p-5 shadow-sm">
      <Icon size={22} className="mb-3 text-[#7F1D1D]" />
      <p className="text-gray-500 text-xs uppercase tracking-wide">{label}</p>
      <h3 className="font-black text-2xl text-gray-900 mt-1">{value}</h3>
    </div>
  );
}

function Row({ label, value }) {
  return (
    <tr>
      <td className="border border-gray-200 p-4 font-semibold bg-gray-50 text-gray-700">
        {label}
      </td>
      <td className="border border-gray-200 p-4 text-gray-900 font-medium">
        {value}
      </td>
    </tr>
  );
}